# Generated by Django 5.1.1 on 2024-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=100)),
                ('translations', models.JSONField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
