# Generated by Django 5.1.1 on 2024-09-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionToVocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_propositions', models.JSONField()),
                ('colloquial_term_propositions', models.JSONField()),
                ('vocabulary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vocabularyitem')),
            ],
        ),
    ]
