# Generated by Django 5.1.1 on 2024-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_suggestiontovocabularyitem_colloquial_term_propositions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiontovocabularyitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
