# Generated by Django 5.1.1 on 2024-10-04 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newwordsuggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newwordsuggestion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_new_word_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestiontovocabularyitem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_vocabulary_suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
