# Generated by Django 5.1.1 on 2024-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_newwordsuggestion_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabularyitem',
            old_name='translations',
            new_name='primary_translations',
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='colloquial_terms',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='definition',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='user_proposed_translations',
            field=models.JSONField(default=dict),
        ),
    ]
