# Generated by Django 5.1.1 on 2024-10-08 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_vocabularyitem_primary_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularyitem',
            name='colloquial_terms',
        ),
        migrations.RemoveField(
            model_name='vocabularyitem',
            name='primary_translations',
        ),
        migrations.RemoveField(
            model_name='vocabularyitem',
            name='user_proposed_translations',
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('translation', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_colloquial', models.BooleanField(default=False)),
                ('is_user_proposed', models.BooleanField(default=False)),
                ('vocabulary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.vocabularyitem')),
            ],
            options={
                'unique_together': {('vocabulary_item', 'language', 'translation')},
            },
        ),
    ]
