# Generated by Django 5.1.1 on 2024-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='savedVocabulary',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
