# Generated by Django 5.1.1 on 2024-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0002_customuser_savedvocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='savedVocabulary',
            field=models.JSONField(default=list),
        ),
    ]
